version: "3.7"

services:
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    restart: "unless-stopped"
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: "unless-stopped"
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS:
      SPA_DEFAULT_LOCALE:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      timeout: 5s
    depends_on:
      - backend

  backend:
    build:
      context: .
    container_name: backend

  db:
    container_name: db
