name: Run on release

on:
  pull_request:
    branches: [main]

jobs:
  generate_docker_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Run Containers
        run: docker-compose -f docker-compose-no-volumes.yml -f docker-compose-no-volumes.override.yml up --build -d

      - name: Wait for the backend to start
        run: while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]; do echo "Waiting for the backend to be up..." sleep 10 done

      - name: Commit and export Containers
        run: ./e2e_support_files/commit_and_export_images.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: /e2e_support_files/e2e_release_env_images.tar


